source 'https://rubygems.org'

gem 'rails', '3.2.5'
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
end

gem 'jquery-rails'
gem 'jquery-rails-multipart-xhr', :path => File.expand_path('../../', File.dirname(__FILE__))